### PR TITLE
Reorg Menus, Add edit on Github, Update the getting started 

### PR DESCRIPTION
**Pull request by jeffpatzer**
- The first get started has people focus on using a Deploy to Layer0 button. This has them create and account and quickly get a project. 
- Reorging menus. The guides sections has exploded and become hard to filter for much of use. 
- Broke out the repeated Node install instructions to its own component and page. 
- Picked a more legible code theme (comments were too faded with the last one)

image
image
image

### CODE REVIEW

**Comment by tristanlee85** [comment]
A few things:

- Why the change of proper titles? Eg: "Getting Started" to "Getting started", etc. There's now a lot of inconsistency between headings. 
- The overview was moved to after the deployment guide. We're now having users build and deploy a project before even knowing what Layer0 is about.

There's a lot of UI changes here regarding the menu structure that I want @markbrocato to review.

**Comment by markbrocato** [comment]
@ianand I think you and the community team should review these changes and decide if there is a better organization of guides. I have my own opinions but I'd rather the community own it.

**Comment by jeffpatzer** [comment]
@tristanlee85 
- Why the change of proper titles? Eg: "Getting Started" to "Getting started", etc. There's now a lot of inconsistency between headings.

Menu items should follow all be sentence case and consistent. 

- The overview was moved to after the deployment guide. We're now having users build and deploy a project before even knowing what Layer0 is about.

Possibly. Up to them to click on which items they want to view first. The overview page as it stands is more of an infrastructure overview anyways. 

Did you have thoughts on the change to the get started page? I think having people trying to use a connector makes more sense off the bat because it 1) gets them a fast deploy without having to use the command line and 2) gets them to create an account in the system with the least amount of friction. 

@markbrocato who is the "community" and how do they weigh in on things? How do we balance moving things forward with getting the correct input?

**Comment by ianand** [comment]
Let's discuss this at standup Friday. Even if it's not perfect its progress on solving the issue that the current menus are getting so large as to be unwieldy.

**Comment by jeffpatzer** [comment]
Included in #88

**Pull request closed without merging**
