### PR TITLE
APPOPS-14467 Change the commands to edgio

### PR DESCRIPTION
**Pull request by petrvecera**
Not sure if we need to do additional changes or this is enough ? If so - that's pretty awesome 🎉 🙌

### CODE REVIEW

**Comment by tristanlee85** [comment]
Good update! This should be all that is needed, but there may be a few places in the docs where someone hardcoded the name. 

When will this package name change be published?

**Review by negyxo — APPROVED** [review]

**Comment by petrvecera** [comment]
> Good update! This should be all that is needed, but there may be a few places in the docs where someone hardcoded the name.
> 
> When will this package name change be published?

@tristanlee85  not sure , we need to sync this release together with the new packages release on NPM with new commands. The release to NPM can happen first because old commands will still be supported as aliases

**Comment by rishi-raj-jain** [comment]
@petrvecera all places: https://github.com/petrvecera/layer0-docs/pull/1, cc @tristanlee85

**Comment by petrvecera** [comment]
Close this in favor of https://github.com/layer0-docs/layer0-docs/pull/511/filesa

**Pull request closed without merging**
