### PR TITLE
Styles and Version

### PR DESCRIPTION
**Pull request by jeffpatzer**
- Fix version links in nav
- Fixes home page styles in Safari
image

### CODE REVIEW

**Comment by jeffpatzer** [comment]
Version links in the left column aren't updated. Will update in another PR

**Comment by jeffpatzer** [comment]
@tristanlee85 this should be good now, fixes both issues of layout and the version links in the hav

**Comment by tristanlee85** [comment]
@jeffpatzer is there a reason the changelog was removed from the home page? Was this by request?

**Comment by jeffpatzer** [comment]
@tristanlee85 I talked to Ishan about it. It makes the homepage super long and usually isn't a homepage item for docs. Changelog is easily found under the "Reference" section.

**Pull request merged**
