### PR TITLE
Rearrange the navigation

### PR DESCRIPTION
**Pull request by RaeesBhatti**
Rearrange left sidebar navigation based on functionality/concern.

### CODE REVIEW

**Comment by rishi-raj-jain** [comment]
Another much needed change.

**Comment by RaeesBhatti** [comment]
Image Optimization probably needs to be moved out of Developer Tools and into App Edge. @jsernaque 
Screen Shot 2022-07-20 at 8 28 41 PM

**Comment by RaeesBhatti** [comment]
This should be "Limits and Caveats" or maybe we can split it into two pages. One regarding App Edge limits and one regarding App Platform limits. Plus caveats for App Platform usage. @jsernaque 

Screen Shot 2022-07-20 at 8 30 49 PM

**Comment by jsernaque** [comment]
WRT "Limits & Caveats", we should eventually split that content by product and move it to the appropriate section.

**Pull request merged**
