### PR TITLE
Theme updates

### PR DESCRIPTION
**Pull request by jeffpatzer**
View PR #50 for details
This adds
- If on index, the first menu is open
- Fixes showing / hiding icons

### CODE REVIEW

**Comment by rishi-raj-jain** [comment]
There's a difference of highlighting (with the theme color) the sidebar item when one opens [overview](https://layer0-docs-xdn-docs-default.layer0.link/guides/overview) directly (in this case the pink color is not visible) vs going to the [docs page](https://layer0-docs-xdn-docs-default.layer0.link/guides/overview), and then selecting overview (in this case the color is visible).

**Comment by rishi-raj-jain** [comment]
Section enhancements  seems to be distorted vs the live documentation at [Screenshot 2021-09-19 at 5 23 34 AM](https://docs.layer0.co/#section___enhancements)

**Comment by rishi-raj-jain** [comment]
Also, in the [vue guide's example section](https://layer0-docs-xdn-docs-default.layer0.link/guides/vue#section_example), the theme button for "Try the Vue Example Site" is not same as in [nuxt guide's example section](https://layer0-docs-xdn-docs-default.layer0.link/guides/nuxt#section_example_ssr_site). Well, I PR'd the changes in vue guide but not able to see what's different in nuxt guide vs the vue guide to get that theme button running.

**Comment by jeffpatzer** [comment]
Rishi
- Good catch on the nav highlight. That is _not_ happening locally. Looks like a hook order / render issue, but hard to test that locally and get a good fix. Pushed up a quick change to see if that does it. It looks like you need to navigate past one page to trigger that render. 
- Adding some padding for the changelog area
- Looks like the links were missing the `?button` query param. I just put that in there to add it.

**Review by tristanlee85 — DISMISSED** [review]

**Review by tristanlee85 — APPROVED** [review]

**Pull request merged**
